### PR TITLE
add 'equal' filter

### PR DESCRIPTION
**Pull request by p2227**
generally we have three value '1','2','3'. and we want to show page 2 but hide 1 and 3.it's easy to do it by this filter.

### CODE REVIEW

**Comment by p2227** [comment]
ok,I got it. btw,it's needed to run uglify ?

**Comment by gmac** [comment]
Mind getting this mergable?

**Comment by gmac** [comment]
Sorry, got looking at the implementation and realized there's a lot more going on here than just asserting that two values are equal. With the three inputs and a polymorphic return value, this feeling highly specific, and therefore better implemented as a custom filter than a baseline feature of the library.

**Comment by p2227** [comment]
so,you think that the implementation is too complex? a filter should do one thing and keep it as simple as possible？

**Pull request closed without merging**
